spring.application.name=card-login

# DB 주소 - 끝에 DB명
spring.datasource.url=jdbc:postgresql://localhost:5432/dotDB

# DB 로그인 아이디/비번
spring.datasource.username=postgres
spring.datasource.password=123

# 기존 테이블 구조 못 바꾸게
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# always: 서버가 켜질 때마다 SQL 파일 실행
spring.sql.init.mode=always

# JPA가 테이블 만들기 전에 SQL 실행되는 거 방지
spring.jpa.defer-datasource-initialization=true